/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualizador.gui;
import java.awt.HeadlessException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author Silvia
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NuevaJFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        Panel_Scroll = new javax.swing.JScrollPane();
        Lista = new javax.swing.JList<>();
        Etiqueta = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Barra_Herramientas = new javax.swing.JToolBar();
        Boton_Herramientas = new javax.swing.JButton();
        Boton = new javax.swing.JButton();
        Panel_Estado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        status_Label = new javax.swing.JTextPane();
        Barra_Menu = new javax.swing.JMenuBar();
        Aplicacion_Menu = new javax.swing.JMenu();
        Salida_Menu = new javax.swing.JMenuItem();
        Ayuda_Menu = new javax.swing.JMenu();
        Informacion_Menu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JarMiApp");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/visualizador/gui/Mojave.png")).getImage());

        Lista.setBackground(new java.awt.Color(0, 0, 0));
        Lista.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Panel_Scroll.setViewportView(Lista);

        Etiqueta.setText("Archivo");

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });

        Barra_Herramientas.setBackground(new java.awt.Color(255, 255, 255));
        Barra_Herramientas.setRollover(true);

        Boton_Herramientas.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/visualizador/gui/Soldadito.png")).getImage().getScaledInstance(16, 16, java.awt.Image.SCALE_SMOOTH)));
        Boton_Herramientas.setText("Mirar");
        Boton_Herramientas.setFocusable(false);
        Boton_Herramientas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Boton_Herramientas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Boton_Herramientas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_HerramientasActionPerformed(evt);
            }
        });
        Barra_Herramientas.add(Boton_Herramientas);

        Boton.setText("Ver Contenido");
        Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Boton)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Panel_Scroll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Barra_Herramientas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Barra_Herramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(Panel_Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        Panel_Estado.setBorder(javax.swing.BorderFactory.createTitledBorder("Vista Previa"));

        status_Label.setEditable(false);
        status_Label.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(status_Label);

        javax.swing.GroupLayout Panel_EstadoLayout = new javax.swing.GroupLayout(Panel_Estado);
        Panel_Estado.setLayout(Panel_EstadoLayout);
        Panel_EstadoLayout.setHorizontalGroup(
            Panel_EstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_EstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel_EstadoLayout.setVerticalGroup(
            Panel_EstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_EstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        Aplicacion_Menu.setText("Aplicación");

        Salida_Menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Salida_Menu.setText("Salir");
        Salida_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salida_MenuActionPerformed(evt);
            }
        });
        Aplicacion_Menu.add(Salida_Menu);

        Barra_Menu.add(Aplicacion_Menu);

        Ayuda_Menu.setText("Ayuda");

        Informacion_Menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        Informacion_Menu.setText("Información");
        Informacion_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Informacion_MenuActionPerformed(evt);
            }
        });
        Ayuda_Menu.add(Informacion_Menu);

        Barra_Menu.add(Ayuda_Menu);

        setJMenuBar(Barra_Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Panel_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(Panel_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActionPerformed
        AnalizarJarFile();
    }//GEN-LAST:event_BotonActionPerformed

    private void AnalizarJarFile() throws HeadlessException {
        status_Label.setText("Analizando ficheros JAR");
        try{
            DefaultListModel model = new DefaultListModel();
            ZipInputStream zip = new ZipInputStream(new FileInputStream(Nombre.getText()));
            for(ZipEntry entry = zip.getNextEntry(); entry != null; entry = zip.getNextEntry()){
                model.addElement(entry.getName());
            }
            Lista.setModel(model);
            
            status_Label.setText("- Ficheros detectados 'L', : " +model.size());
        }catch(IOException ioe){
            status_Label.setText("- Archivos encontrados: 0");
            JOptionPane.showMessageDialog(this, ioe.getLocalizedMessage(), "'L'. ¡UPS! - Errorcito a la vista", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void Boton_HerramientasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_HerramientasActionPerformed
        AnalizarJarFile();
    }//GEN-LAST:event_Boton_HerramientasActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void Salida_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salida_MenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Salida_MenuActionPerformed

    private void Informacion_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Informacion_MenuActionPerformed
        DialogoApp dialog = new DialogoApp(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_Informacion_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Aplicacion_Menu;
    private javax.swing.JMenu Ayuda_Menu;
    private javax.swing.JToolBar Barra_Herramientas;
    private javax.swing.JMenuBar Barra_Menu;
    private javax.swing.JButton Boton;
    private javax.swing.JButton Boton_Herramientas;
    private javax.swing.JLabel Etiqueta;
    private javax.swing.JMenuItem Informacion_Menu;
    private javax.swing.JList<String> Lista;
    private javax.swing.JTextField Nombre;
    private javax.swing.JPanel Panel;
    private javax.swing.JPanel Panel_Estado;
    private javax.swing.JScrollPane Panel_Scroll;
    private javax.swing.JMenuItem Salida_Menu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane status_Label;
    // End of variables declaration//GEN-END:variables
}

